### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by aleksandraDev** [jciccio/react-table-with-csv-download#11]
Hey, thanks for this library, you saved me ! :)

I just couldn't make Search field work. Is there any additional setup or it's just a bug ? Can you, please, check it ?
And if it's possible to remove all console.log, please, it's hard to have console for debugging clean.

Thanks a lot in advance and thanks again for this package ! ;)
Cheers !

**Comment by jciccio** [comment]
Hi, 

can you provide me more info about the bug? Like the config used please?
an will totally clean up the console logs :)

**Comment by aleksandraDev** [comment]
Thanks for quick reply ! :)

I am using the latest Create React App with React Hooks and :
`{
   "react": "^16.12.0",
   "react-dom": "^16.12.0",
}`

I put `searchEnabled` as an option, I got the search field but I don't have any results by typing in the search box 
`
<TableViewer
        title={title}
        content={table}
        headers={headers}
        minHeight={0}
        maxHeight={600}
        activateDownloadButton={true}
        downloadButtonStyle={{ cursor: 'pointer' }}
        filename={`${title}-${getDate}.csv`}
        searchEnabled
      />
`
What did I do wrong ? :) Do you need more details ?

(I will have another demand ... :-|  I need option for delimiter in CSV file that I download. My CSV file needs to be with " ; " so that people for business can use it correctly in Excel . Should I open another issue ? )

Thanks for everything !! :)

**Comment by jciccio** [comment]
It is working for me, but it is case sensitive. Can you check with the example to see if it is working for you?

In case casing is an issue, you can send the prop: `caseInsensitive in false` that should do the trick. Let me know if it works :)

**Comment by aleksandraDev** [comment]
I tried with caseInsensitive in combination with other props, but it worked just with `pagination` in fact, I don't know why. If I figure out, I'll let you know. :)
Thanks again ! ;)

**Comment by jciccio** [comment]
Were you able to figure it out?
